import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionAuthProvider from "@/context/SessionAuthProvider";
import axios from "axios";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

axios.defaults.baseURL =
  "https://bookreviewsapp20240204232531.azurewebsites.net/api/";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionAuthProvider>
          <NavBar />
          {children}
        </SessionAuthProvider>
      </body>
    </html>
  );
}
